name: format
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Format internal playlists
        run: npm run playlist:format

      - name: Check internal playlists
        run: |
          npm run playlist:lint
          npm run playlist:validate

      - name: Get list of changed files
        id: files_after
        run: |
          ANY_CHANGED=false
          ALL_CHANGED_FILES=$(git diff --diff-filter=ACMRT --name-only HEAD -- streams/ | tr '\n' ' ')
          if [ -n "${ALL_CHANGED_FILES}" ]; then
            ANY_CHANGED=true
          fi
          echo "all_changed_files=$ALL_CHANGED_FILES" >> "$GITHUB_OUTPUT"
          echo "any_changed=$ANY_CHANGED" >> "$GITHUB_OUTPUT"

      - name: Setup git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit changes to /streams
        if: steps.files_after.outputs.any_changed == 'true'
        run: |
          git add streams
          git status
          git commit -m "chore: format streams" --no-verify

      - name: Push all changes to the repository
        if: github.ref == 'refs/heads/master' && steps.files_after.outputs.any_changed == 'true'
        run: git push
